wpeverest/user-registration-pro@UR-3432-new-styles-colors-support-to-support-site-brand:
  - assets
  - includes
  - modules
  - src
  - templates
  - .babelrc
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .jshintrc
  - license.txt
  - phpcs.xml
  - uninstall.php
  - webpack.config.js
  - wpml-config.xml
  
