wpeverest/user-registration-pro@UR-4500-tweak/compatibility-with-latest-divi-release:
    - src: assets
      exclude: |
        js/divi-vb-modules.js
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
