wpeverest/user-registration-pro@release/UR-2954-release-issue-fix-for-4-4-0-yl:
  - assets
  - includes
  - modules
  - src
  - templates
  - .babelrc
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .jshintrc
  - license.txt
  - phpcs.xml
  - uninstall.php
  - webpack.config.js
  - wpml-config.xml
