wpeverest/user-registration-pro@UR-3342-enhance/integrating-all-existing-email-marketing-addons-to-membership-plans:
  - assets
  - includes
  - modules
  - src
  - templates
  - .babelrc
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .jshintrc
  - license.txt
  - phpcs.xml
  - uninstall.php
  - webpack.config.js
  - wpml-config.xml
