wpeverest/user-registration-pro@UR-749-merge-two-duplicate-methods-on-ur-form-validation:
      - assets
      - includes
      - src
      - templates
      - .babelrc
      - .distignore
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .jshintrc
      - license.txt
      - phpcs.xml
      - uninstall.php
      - webpack.config.js
      - wpml-config.xml
