wpeverest/user-registration-pro@UR-4147-fix/fatal-error-on-payment-history-page-get-order-detail-called-on-string:
    - assets
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
