wpeverest/user-registration-pro@UR-1917-login-form-design-tweak-according-to-improvised-design:
      - assets
      - includes
      - src
      - templates
      - .babelrc
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .jshintrc
      - license.txt
      - phpcs.xml
      - uninstall.php
      - webpack.config.js
      - wpml-config.xml
