wpeverest/user-registration-pro@UR-2656-custom-email:
  - assets
  - includes
  - modules
  - src
  - templates
  - .editorconfig
  - .gitattributes
  - .gitignore
  - license.txt
  - phpcs.xml
  - uninstall.php
  - wpml-config.xml
