wpeverest/user-registration-pro@URM-729-phase-1-design-fixes:
  - assets
  - includes
  - modules
  - src
  - templates
  - .babelrc
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .jshintrc
  - license.txt
  - phpcs.xml
  - uninstall.php
  - webpack.config.js
  - wpml-config.xml
