wpeverest/user-registration-pro@UR-4172-fix/price-created-on-every-registration-in-stripe:
    - assets
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
