wpeverest/user-registration-pro@UR-4134-fix/auto-approval-auto-login-option-not-working-in-case-of-pay-pal-payments:
    - assets
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
