wpeverest/user-registration-pro@UR-2379-enhancement-request-separate-payment-settings-save-mechanism-for-each-payment-module:
  - assets
  - includes
  - modules
  - src
  - templates
  - .babelrc
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .jshintrc
  - license.txt
  - phpcs.xml
  - uninstall.php
  - webpack.config.js
  - wpml-config.xml
