wpeverest/user-registration-pro@UR-3778-fix/user-email-update-issue:
    - assets
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
