wpeverest/user-registration-pro@fix/vulnerability-v5.2.1:
    - assets
    - includes
    - modules
    - src
    - templates
    - .editorconfig
    - .gitattributes
    - .gitignore
    - license.txt
    - phpcs.xml
    - uninstall.php
    - wpml-config.xml
