wpeverest/user-registration-pro@new/about-page:
      - assets
      - includes
      - src
      - templates
      - .babelrc
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .jshintrc
      - license.txt
      - phpcs.xml
      - uninstall.php
      - webpack.config.js
      - wpml-config.xml
