name: Copilot review on comment

on:
  issue_comment:
    types: [created]

jobs:
  review:
    uses: wpeverest/.github/.github/workflows/copilot-review-on-comment.yml@master
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
