name: Build pre-release 
on:
  release:
    types: [published]
jobs:
  tag:
    name: New tag
      if:${{github.event.release.prerelease == true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Build
        id: build
        uses: wpeverest/action-build@3.0.0
        with:
          generate-zip: true
